### ISSUE TITLE
Suggestion: Remove and/or Edit buttons

### ISSUE THREAD

**Issue by KadTheHunter** [ChampOfGames/NotesUI#1]
Add a button to remove notes, and/or a button to edit notes. It would be easier than having the server Owner go delete the files manually...

**Comment by champmq** [comment]
I will add it in the next version.

**Comment by KadTheHunter** [comment]
Great :)

**Comment by champmq** [comment]
I added the feature but didnt have the time to test it so you can try it but I can also send a message here after I tested it.

**Comment by KadTheHunter** [comment]
2 Issues:

1st Issue:
`[14:22:36] [Server thread/CRITICAL]: ErrorException: "unlink(/home/container/plugin_data/NotesUI/KadTheHunter/Test .txt): No such file or directory" (EXCEPTION) in "plugins/NotesUI_dev-12.phar/src/ChampOfGames/NotesUI/Main" at line 116 `
I believe the issue is it says `Test .txt` not `Test.txt`
2nd Issue:
The button had `$4` rather than `§4`

**Comment by champmq** [comment]
Should be fixxed now

**Comment by KadTheHunter** [comment]
`[16:18:01] [Server thread/CRITICAL]: ErrorException: "unlink(/home/container/plugin_data/NotesUI/KadTheHunter//home/container/plugin_data/NotesUI/KadTheHunter/Test.txt.txt): No such file or directory" (EXCEPTION) in "plugins/NotesUI_dev-14.phar/src/ChampOfGames/NotesUI/Main" at line 117`

Now it says `Test.txt.txt`

Maybe changing line 131 from
`$this->delNote($player->getName() ,$this->files2[$data[0]]. ".txt");`
to
`$this->delNote($player->getName() ,$this->files2[$data[0]])` would work?

**Comment by champmq** [comment]
Yeah, I forgot to remove the .txt part, but it should work now

**Comment by KadTheHunter** [comment]
Now it has 
`[21:01:12] [Server thread/CRITICAL]: ErrorException: "unlink(/home/container/plugin_data/NotesUI/KadTheHunter//home/container/plugin_data/NotesUI/KadTheHunter/Test.txt): No such file or directory" (EXCEPTION) in "plugins/NotesUI_dev-15.phar/src/ChampOfGames/NotesUI/Main" at line 117 `

Something I now notice that I didnt notice earlier is it repeats the file _path_ 
`home/container/plugin_data/NotesUI/KadTheHunter//home/container/plugin_data/NotesUI/KadTheHunter/Test.txt`
and it should be
`/home/container/plugin_data/NotesUI/KadTheHunter/Test.txt`

**Comment by champmq** [comment]
That should be the last error thanks for your help with testing the plugins

**Comment by KadTheHunter** [comment]
Apparently not :|

`[14:45:25] [Server thread/CRITICAL]: ErrorException: "unlink(KadTheHunter//home/container/plugin_data/NotesUI/KadTheHunter/Test.txt): No such file or directory" (EXCEPTION) in "plugins/NotesUI_dev-16.phar/src/ChampOfGames/NotesUI/Main" at line 117`

**Comment by champmq** [comment]
Is the path right so the part with container

**Comment by KadTheHunter** [comment]
Yes it's `/home/container/plugin_data/NotesUI/` and within that `KadTheHunter/Test.txt`
I guess the issue now is the extra `KadTheHunter/` at the very beginning.

**Comment by champmq** [comment]
Could you test it again?

**Comment by KadTheHunter** [comment]
Tried Dev #17:

`[16:41:06] [Server thread/CRITICAL]: ErrorException: "unlink(KadTheHunter//home/container/plugin_data/NotesUI//Test.txt): No such file or directory" (EXCEPTION) in "plugins/NotesUI_dev-17.phar/src/ChampOfGames/NotesUI/Main" at line 117`

Looks like it's taking `KadTheHunter/` and moving it to the beginning instead of between `/NotesUI/` and `Test.txt`

Broken (and current) version: `KadTheHunter//home/container/plugin_data/NotesUI//Test.txt`
Proper version: `/home/container/plugin_data/NotesUI/KadTheHunter/Test.txt`

Also seems to be adding an extra slash, as if you simply moved `KadTheHunter/` to where it should be you would have `KadTheHunter//Test.txt` with 2 slashes.

**Comment by champmq** [comment]
Yeah didnt see that but I hope this is the last test

**Comment by KadTheHunter** [comment]
Yes! It works perfectly now. Thank you :)
